# Generated by Django 5.2.4 on 2025-08-02 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_city_userprofile_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='oauth_provider',
            field=models.CharField(blank=True, choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=50, null=True),
        ),
    ]
