# Generated by Django 5.2.4 on 2025-08-02 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_oauth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='oauth_provider',
        ),
    ]
